spring.application.name=assistant
#
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
#
spring.ai.model.embedding=bedrock-cohere
# theres even a jetbrains model!
spring.ai.bedrock.converse.chat.options.model=amazon.nova-pro-v1:0
#
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost/mydatabase

#
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


#
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.initialize-schema=true
#
##
## MCP
spring.ai.mcp.client.sse.connections.scheduler.url=http://localhost:8081
#
spring.threads.virtual.enabled=true

